NNTF support
keboola/db-extractor-snowflake pull request #141
Opened 2024-06-20 09:44 UTC by AdamVyborny

JIRA: https://keboola.atlassian.net/browse/PST-1418

2024-06-20 13:15 UTC, zajca commented
ty vole co je to za zkratku nntf :D za měsíc nebudeš vědět co to je :D

2024-06-21 11:38 UTC, ondrajodas approved these changes
jo dobrý, jen opravdu bych i ten test přejmenoval na run-action-native-types-manifest

2024-06-21 11:43 UTC, ondrajodas requested changes
vlastně ne dobrý... jedna věc

2024-06-21 11:43 UTC, ondrajodas commented on tests/functional/run-action-nntf-manifest/expected/data/out/tables/in.c-main.escaping.csv.gz.manifest
> +                    "type": "VARCHAR"
tohle není base type, ale `snowflake` type... base type je STRING

2024-07-05 10:34 UTC, merged